dist: xenial
sudo: false

language: python

branches:
  only:
  - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.7
      env: TOXENV=py37
    - python: pypy2.7-6.0
      env: TOXENV=pypy

install:
  - pip install -U tox

script:
  - tox
